# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(default='UNINITIALIZED', max_length=50),
            preserve_default=False,
        ),
    ]
